### ISSUE TITLE
Prefix breaks in version 0.3.20

### ISSUE THREAD

**Issue by Novtopro** [lutaml/lutaml-model#152]
In version 0.3.19, the spec below works as expected

![CleanShot 2024-11-06 at 09 29 31@2x](https://github.com/user-attachments/assets/8cd9c29e-dc09-415b-a7ec-0921d08200b9)

but in 0.3.20 and above, it does not

![CleanShot 2024-11-06 at 09 32 04@2x](https://github.com/user-attachments/assets/d8a85d95-9f70-4959-9b5c-fa52bc6fc487)

The prefix is gone. 

FYI @ronaldtse @HassanAkbar 

Can be reproduced in https://github.com/metanorma/niso-jats/pull/19 by updating the gem version.

**Comment by ronaldtse** [comment]
Thank you @Novtopro for the report. This was exactly why I was worried about the fix for #150 because inner elements were not tested. 

@HassanAkbar @suleman-uzair can we fix this ASAP with additional specs as mentioned in #151 ?

**Comment by ronaldtse** [comment]
@HassanAkbar ok I am a bit confused with namespace behavior.

This is the [XML Namespaces specification](https://www.w3.org/TR/xml-names/).

The "fully namespaced name" of an element name or an attribute, which contains a "namespace name" and a "local name" is called the ["expanded name"](https://www.w3.org/TR/xml-names/#dt-expname).

Look at 6.2, the "larger example":

```xml
<?xml version="1.0"?>
<!-- initially, the default namespace is "books" -->
<book xmlns='urn:loc.gov:books'
      xmlns:isbn='urn:ISBN:0-395-36341-6'>
    <title>Cheaper by the Dozen</title>
    <isbn:number>1568491379</isbn:number>
    <notes>
      <!-- make HTML the default namespace for some commentary -->
      <p xmlns='http://www.w3.org/1999/xhtml'>
          This is a <i>funny</i> book!
      </p>
    </notes>
</book>
```

If a "default namespace" is defined at a parent element, all unprefixed child elements are supposed to be of the same namespace.

* "title" is actually "urn:loc.gov:books:title".
* "notes" is "urn:loc.gov:books:notes".

If a "default namespace" is defined on an element inside a tree that has a "default namespace" already defined, only the closest "default namespace" is used.

* "p" is "http://www.w3.org/1999/xhtml:p"
* "i" is "http://www.w3.org/1999/xhtml:i"

In the next example:
```xml
<?xml version='1.0'?>
<Beers>
  <!-- the default namespace inside tables is that of HTML -->
  <table xmlns='http://www.w3.org/1999/xhtml'>
   <th><td>Name</td><td>Origin</td><td>Description</td></th>
   <tr> 
     <!-- no default namespace inside table cells -->
     <td><brandName xmlns="">Huntsman</brandName></td>
     <td><origin xmlns="">Bath, UK</origin></td>
     <td>
       <details xmlns=""><class>Bitter</class><hop>Fuggles</hop>
         <pro>Wonderful hop, light alcohol, good summer beer</pro>
         <con>Fragile; excessive variance pub to pub</con>
         </details>
        </td>
      </tr>
    </table>
  </Beers>
```

When a namespace is set to the empty string "", then the applicable default namespace is cleared (no namespace).

* "brandName", "origin", "details" have no namespace.

According to 6.3, "default namespace does not apply to attribute names":

```xml
<!-- http://www.w3.org is bound to n1 and is the default -->
<x xmlns:n1="http://www.w3.org" 
   xmlns="http://www.w3.org" >
  <good a="1"     b="2" />
  <good a="1"     n1:a="2" />
</x>
```

Therefore
* "a", "b" have no namespace.
* "n1:a" has namespace of "n1:http://www.w3.org"
* "x" tag, "good" tag have the namespace of "http://www.w3.org"

We should obviously use these examples as specs.

**Comment by ronaldtse** [comment]
@Novtopro I believe this problem has been resolved in 0.3.24. Could you help check? Thanks!

**Comment by Novtopro** [comment]
The issue is still there
![CleanShot 2024-11-15 at 09 43 03@2x](https://github.com/user-attachments/assets/8f6498b3-9279-4aab-b3c3-ab046b901be3)

![CleanShot 2024-11-15 at 09 44 02@2x](https://github.com/user-attachments/assets/454e5e71-265f-4763-9f81-0b5963e205f1)

FYI @ronaldtse @HassanAkbar

**Comment by ronaldtse** [comment]
Thanks @Novtopro !
